// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// backend/prisma.config.ts
// backend/prisma.config.ts
import { defineConfig } from '@prisma/config';
import * as dotenv from 'dotenv';
import * as path from 'path';

// Força o dotenv a buscar o arquivo .env exatamente na raiz da pasta backend
dotenv.config({ path: path.resolve(__dirname, '.env') });

// Log de segurança temporário (Remova após funcionar)
if (!process.env.DATABASE_URL) {
  console.error(
    '\x1b[31m%s\x1b[0m',
    '⚠️ ERRO: A variável DATABASE_URL não foi carregada do arquivo .env!',
  );
}

export default defineConfig({
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
